@file:Suppress("unused")
package hamusutax.formats.clashconfig.model

enum class RuleType {
    DOMAIN,
    DOMAIN_SUFFIX,
    DOMAIN_KEYWORD,
    DOMAIN_REGEX,
    GEOSITE,
    IP_CIDR,
    IP_CIDR6,
    IP_SUFFIX,
    IP_ASN,
    GEOIP,
    SRC_GEOIP,
    SRC_IP_ASN,
    SRC_IP_CIDR,
    SRC_IP_SUFFIX,
    DST_PORT,
    SRC_PORT,
    IN_PORT,
    IN_TYPE,
    IN_USER,
    IN_NAME,
    PROCESS_PATH,
    PROCESS_PATH_REGEX,
    PROCESS_NAME,
    PROCESS_NAME_REGEX,
    UID,
    NETWORK,
    DSCP,
    RULE_SET,
    AND,
    OR,
    NOT,
    SUB_RULE,
    MATCH
}
